language: c++
before_script:
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2
  - tar jxf wxWidgets-3.1.0.tar.bz2
  - (cd wxWidgets-3.1.0 && ./configure --prefix=$HOME/wx-3.1.0 && make -j2 all install)
  - ln -s $HOME/wx-3.1.0/bin/wx-config $HOME/wx-3.1.0/bin/wx-config-3
  - user=$(echo $TRAVIS_REPO_SLUG | sed 's,/.*$,,')
  - cd ../ 
  - git clone https://github.com/$user/lk /home/travis/build/$user/lk

script:
  - export PATH=$PATH:$HOME/wx-3.1.0/bin
  - cd $HOME/travis/build/$user
  - make -j2 -C lk/build_linux
  - make -j2 -C wex/build_linux

install:
  - sudo apt-get install -y libgtk-3-dev
